-- create database customer_behaviour_analysis;
 use customer_behaviour_analysis;
-- Q1 what is the total revenue generated by male and female
select Gender,
sum(Purchase_Amount) as revenue 
from  customer_analysis 
group by Gender ;

-- Q2 which customer used a discount but still spent more than the average purchase amout(APA)

select Customer_ID , Purchase_Amount,Discount_Applied from customer_analysis where
Discount_Applied = "Yes" and Purchase_Amount>=(select avg(Purchase_Amount) from customer_analysis);

-- Q3 what are top 5 product with highest avg review rating
select Item_Purchased , round(avg(Updated_Review)) as Avg_Review 
from customer_analysis 
group by Item_Purchased
 order by Avg_Review desc limit 5;
 
-- Q4 Compare average purchse amount b/w standard and express shipping
select Shipping_Type , avg(Purchase_Amount) as avg_purchase_amount
from customer_analysis 
where Shipping_Type in ("Standard","Express")
group by Shipping_Type;

-- Q5 Do subscribed customers spend more ? compare average spend and total revenue b/w subscriber and non - subscriber
select Subscription_Status ,
 sum(Purchase_Amount) as revenue ,
 avg(Purchase_Amount) as average
 from  customer_analysis 
 group by Subscription_Status;
 
-- Q6 Which 5 product have the highest percentage of purchases with dicount applied?
select  Item_Purchased, sum(Purchase_Amount) as amount ,
Discount_Applied from customer_analysis
where Discount_Applied = "Yes" group by Item_Purchased,Discount_Applied order by amount limit 5;

-- Q7 segment customer into new, returning and loyal based on their total numbers of previous purchase
-- and show the count of each segment
select Customer_ID, Previous_Purchases ,
case 
when Previous_Purchases between 0 and 10 then "New"
when Previous_Purchases between 11 and 25 then "Loyal"
when Previous_Purchases between 26 and 50 then  "Returning"
else "other"
end as Customer_Segment from customer_analysis;

-- Q8 What are the top 3 most purchased products within each category?
with cte as (select Item_Purchased,Category,
count(Customer_ID) as total_orders ,row_number() over(partition by Category order by 
count(Customer_ID) desc) as item_rnk from customer_analysis
group by Item_Purchased,Category
)
select item_rnk ,Category , item_Purchased , total_orders
from cte 
where item_rnk <=3;	

-- Q9 Are customer who are repeat buyers more than 5 previous purchase also
-- likely to subscribers
select Subscription_Status,count(Customer_ID) as repeat_buyers
from customer_analysis 
where  Previous_Purchases > 5
group by Subscription_Status;

-- Q10 What is the revenue contribution of each age group 
select Age_Label,sum(Purchase_Amount) as revenue from customer_analysis
group by Age_Label
 




